global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using KC.HMS.Core.Abstracts;
global using KC.HMS.Core.Contracts;
global using KC.HMS.Core.Contexts;
global using KC.HMS.Core.Middlewares;
global using KC.HMS.Core.Models;
